### ISSUE TITLE
Importing error & videos don't play :(

### ISSUE THREAD

**Issue by K1NGM4RV** [blinry/anki-german-sign-language#2]
It shows the following Error code

```
Import failed. Debugging info:
Invalid input: ⁨note has 20 fields, expected 14⁩
```
Besides the unfortunately videos unfortunately don't play.

Your work and help is appreciated! Don't let this amazing deck go to waste :)
//I'm using Anki 2.1.45 on windows (no modifications)

**Comment by SamuelVilz** [comment]
As far as I know, videos only play on certain devices. I know that they work on AnkiDroid, and not on Windows.
Also, you might want to check out my fork, where I fixed some stuff :)
https://github.com/SamuelVilz/anki-german-sign-language

**Comment by K1NGM4RV** [comment]
Thanks for your help @SamuelVilz, the problem is that I want to utilize my PC instead of my phone. 
As soon as I have the time I will look into it and see if I can create a deck that supports proper video playback everywhere.
